## Pre-commit setup
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      # Ensures that a file is either empty, or ends with one newline.
      - id: end-of-file-fixer

      # Remove trailing whitespace
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]

  # Code style and formatting
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.0.280
    hooks:
      - id: ruff

  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
        args: [
          --line-length, "120",
          ]

  - repo: https://github.com/HunterMcGushion/docstr_coverage
    rev: v2.3.0
    hooks:
      - id: docstr-coverage
        args: ["--verbose", "2"] # override the .docstr.yaml to see less output

  # # Security and Vulnerability checks
  # - repo: https://github.com/Lucas-C/pre-commit-hooks-bandit
  #   rev: v1.0.6
  #   hooks:
  #   -   id: python-bandit-vulnerability-check
  #       args: [--skip, "B101", --recursive, clumper]
